# disable FutureWarning
import warnings
warnings.filterwarnings("ignore")
warnings.simplefilter(action='ignore')
import argparse
import logging
import os
import yaml
from pathlib import Path

try:
    from lightning.pytorch.callbacks import Callback
except ImportError:
    try:
        from pytorch_lightning.callbacks import Callback
    except ImportError:
        class Callback: pass  # Fallback just in case

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

class StopFileCallback(Callback):
    """
    A callback to monitor for a 'stopfile.txt' at the end of each epoch.
    Matches the custom stopping logic from the original YOLOv5 train.py.
    """
    def __init__(self, stopfile_path="stopfile.txt"):
        super().__init__()
        self.stopfile_path = stopfile_path
        
    def on_train_epoch_end(self, trainer, pl_module):
        if os.path.exists(self.stopfile_path):
            with open(self.stopfile_path, 'r') as f:
                lines = f.readlines()
                for line in lines:
                    if line.strip().lower() == "stop":
                        logger.info("Stop file contains 'stop', stopping training.")
                        trainer.should_stop = True
                        return
                    elif line.strip().isdigit():
                        stop_epoch = int(line.strip())
                        if trainer.current_epoch >= stop_epoch:
                            logger.info(f"Stop file contains epoch {stop_epoch}, stopping training at epoch {trainer.current_epoch}.")
                            trainer.should_stop = True
                            return


def parse_args():
    default_data = './data/hsi/custom_hod_coco.yaml' if os.path.exists('./data/hsi/custom_hod_coco.yaml') else './data/hsi/custom_hod.yaml'
    parser = argparse.ArgumentParser(description="RF-DETR Training Script")
    parser.add_argument('--data', type=str, default=default_data, help='data.yaml path')
    parser.add_argument('--weights', type=str, default='rfdtr-small.pth', help='pretrained weights path')
    parser.add_argument('--model', type=str, default='small', choices=['small', 'large', 'xxlarge'], help='model size')
    parser.add_argument('--stream-mode', type=str, default='rgb', choices=['rgb', 'ir', 'stack', 'dual'], 
                        help='stream strategy: rgb (default 3ch), ir (3ch), stack (pseudo 3ch), dual (6ch)')
    parser.add_argument('--img-size', type=int, default=576, help='image size (must be divisible by 32)')
    parser.add_argument('--batch-size', type=int, default=2, help='total batch size')
    parser.add_argument('--device', default='0', help='cuda device, i.e. 0 or 0,1,2,3 or cpu')
    parser.add_argument('--epochs', type=int, default=100, help='number of epochs')
    parser.add_argument('--name', default='exp', help='save to project/name')
    parser.add_argument('--project', default='project/rfdetr/train', help='save to project/name')
    parser.add_argument('--resume', type=str, default=None, help='resume from checkpoint')
    parser.add_argument('--workers', type=int, default=8, help='maximum number of dataloader workers')
    parser.add_argument('--gradient-checkpointing', action='store_true', help='enable gradient checkpointing')
    parser.add_argument('--wandb', action='store_true', help='use wandb logging')
    parser.add_argument('--tensorboard', action='store_true', default=True, help='use tensorboard logging')
    return parser.parse_args()


def main():
    
    opt = parse_args()
    
    # 1. Parse data.yaml
    logger.info(f"Loading data config from {opt.data}")
    with open(opt.data, 'r') as f:
        data_dict = yaml.safe_load(f)
    
    num_classes = int(data_dict.get('nc', 1))
    class_names = data_dict.get('names', [f'class_{i}' for i in range(num_classes)])
    
    # 2. Resolve dataset directory based on stream-mode
    train_rgb_path = Path(data_dict.get('train_rgb', ''))
    train_ir_path = Path(data_dict.get('train_ir', ''))
    
    num_channels = 3
    if opt.stream_mode == 'rgb':
        stream_path = train_rgb_path
    elif opt.stream_mode == 'ir':
        stream_path = train_ir_path
    elif opt.stream_mode == 'stack':
        # stack_information was pre-generated by convert_dataset_rfdetr.py
        # Each image is a 3-ch pseudo: [gray(SE), gray(SA), |gray(SE)-gray(SA)|]
        train_stack_raw = data_dict.get('train_stack', '')
        if not train_stack_raw:
            raise ValueError(
                "'train_stack' key missing from data YAML. "
                "Re-run convert_dataset_rfdetr.py to generate the stack_information folder."
            )
        stream_path = Path(train_stack_raw)
        logger.info("Stack mode: using pre-merged 3-ch pseudo images from stack_information/")
    elif opt.stream_mode == 'dual':
        # TODO: dual mode requires num_channels=6 + a custom DataModule.
        # Falling back to RGB for now; set up separately.
        stream_path = train_rgb_path
        num_channels = 6
        logger.warning(
            "Dual mode (num_channels=6) selected but a custom 6-ch DataModule is not yet "
            "implemented. Falling back to RGB directory for now. Set up dual mode separately."
        )
    else:
        stream_path = train_rgb_path

    # Determine root directory:
    # If YOLO style: path/to/stream/images/train -> root is path/to/stream (parent of images)
    # If COCO style: path/to/stream/train/       -> root is path/to/stream (parent of train)
    if (stream_path.parent / "train" / "_annotations.coco.json").exists() or (stream_path.parent / "train").exists():
        dataset_dir = stream_path.parent
    elif (stream_path.parent.parent / "train" / "images").exists() or (stream_path.parent.parent / "data.yaml").exists():
        dataset_dir = stream_path.parent.parent
    else:
        # Fallback: check if stream_path itself is the 'train' folder or 'images/train'
        if stream_path.name == "train" and stream_path.parent.name == "images":
            dataset_dir = stream_path.parent.parent
        else:
            dataset_dir = stream_path.parent

    dataset_dir = str(dataset_dir.resolve() if hasattr(dataset_dir, "resolve") else Path(dataset_dir).resolve())
    logger.info(f"Using dataset directory: {dataset_dir} for stream-mode: {opt.stream_mode}")
    
    # 3. Setup output directory
    output_dir = Path(opt.project) / opt.name
    output_dir.mkdir(parents=True, exist_ok=True)
    
    # 4. Initialize Model
    logger.info(f"Initializing RF-DETR '{opt.model}' model... (channels: {num_channels})")
    
    model_kwargs = {
        'pretrain_weights': opt.weights,
        'num_classes': num_classes,
        'resolution': opt.img_size,
        'num_channels': num_channels,
        'gradient_checkpointing': opt.gradient_checkpointing,
    }
    
    if opt.model == 'small':
        from rfdetr import RFDETRSmall
        model = RFDETRSmall(**model_kwargs)
    elif opt.model == 'large':
        from rfdetr import RFDETRLarge
        model = RFDETRLarge(**model_kwargs)
    elif opt.model == 'xxlarge':
        from rfdetr import RFDETRXXLarge
        model = RFDETRXXLarge(**model_kwargs)
    else:
        from rfdetr import RFDETR
        model = RFDETR(**model_kwargs)

    # 5. Add custom callbacks
    # RFDETR maintains a callbacks dictionary matching lightning callback hooks
    if "trainer" not in model.callbacks:
        model.callbacks["trainer"] = []
    model.callbacks["trainer"].append(StopFileCallback())
    
    # 6. Set device/accelerator
    if opt.device == 'cpu':
        accelerator = 'cpu'
        devices = 1
    else:
        accelerator = 'gpu'
        devices = [int(x) for x in str(opt.device).split(',')] if ',' in str(opt.device) else int(opt.device)
        
    # 7. Start Training
    logger.info("Starting RF-DETR training...")
    try:
        
        model.train(
            dataset_dir=dataset_dir,
            epochs=opt.epochs,
            batch_size=opt.batch_size,
            num_workers=opt.workers,
            output_dir=str(output_dir),
            resume=opt.resume,
            accelerator='auto',
            device='cuda',
            wandb=opt.wandb,
            tensorboard=opt.tensorboard,
            class_names=class_names,
            notes=f"Model: {opt.model}, Stream: {opt.stream_mode}",
            grad_accum_steps=2,
            compute_val_loss=True,
            log_per_class_metrics=True,
            lr=5e-5,
        )
    except Exception as e:
        logger.error(f"Training failed: {e}")
        raise

if __name__ == '__main__':
    main()
